#!/usr/bin/env bash
# setup-ntp-sync.sh
# 适用于常见 Linux 发行版：自动安装 chrony、写入国内优先 + 国际冗余 的 NTP 源、启动并强制同步
set -euo pipefail

# ===== 可调整的 NTP 源（国内优先 + 国际冗余） =====
NTP_SERVERS=(
  "ntp.aliyun.com iburst"
  "time1.cloud.tencent.com iburst"
  "time.google.com iburst"
  "time.cloudflare.com iburst"
  "pool.ntp.org iburst"
)

BACKUP_DIR="/root/ntp_backup_$(date +%Y%m%d%H%M%S)"
CHRONY_CONF="/etc/chrony.conf"
SYSTEMCTL=$(command -v systemctl || true)

echo "=== 开始 NTP 配置流程 ==="
echo "备份目录：$BACKUP_DIR"
mkdir -p "$BACKUP_DIR"

# 检测包管理器
PKG_MANAGER=""
if command -v yum >/dev/null 2>&1; then
  PKG_MANAGER="yum"
elif command -v dnf >/dev/null 2>&1; then
  PKG_MANAGER="dnf"
elif command -v apt-get >/dev/null 2>&1; then
  PKG_MANAGER="apt"
else
  echo "未检测到受支持的包管理器（yum/dnf/apt）。请手工安装 chrony 或联系管理员。" >&2
  exit 1
fi
echo "检测到包管理器：$PKG_MANAGER"

# 安装 chrony
install_chrony() {
  echo "安装 chrony..."
  case "$PKG_MANAGER" in
    yum|dnf)
      $PKG_MANAGER -y makecache || true
      $PKG_MANAGER -y install chrony || { echo "安装 chrony 失败，尝试安装 ntp"; $PKG_MANAGER -y install ntp || true; }
      ;;
    apt)
      apt-get update -y
      DEBIAN_FRONTEND=noninteractive apt-get install -y chrony || { echo "安装 chrony 失败，尝试安装 ntp"; DEBIAN_FRONTEND=noninteractive apt-get install -y ntp || true; }
      ;;
  esac
}

install_chrony

# 停用 systemd-timesyncd（如存在）以避免冲突
if command -v systemctl >/dev/null 2>&1 && systemctl list-unit-files | grep -q timesyncd; then
  echo "检测到 systemd-timesyncd，正在停止并禁用..."
  systemctl stop systemd-timesyncd.service 2>/dev/null || true
  systemctl disable systemd-timesyncd.service 2>/dev/null || true
fi

# 备份现有配置
echo "备份现有配置..."
[ -f "$CHRONY_CONF" ] && cp -a "$CHRONY_CONF" "$BACKUP_DIR/chrony.conf.bak"
[ -f /etc/ntp.conf ] && cp -a /etc/ntp.conf "$BACKUP_DIR/ntp.conf.bak" 2>/dev/null || true

# 写入新的 chrony.conf
echo "写入新的 $CHRONY_CONF ..."
cat > "$CHRONY_CONF" <<EOF
# chrony.conf - minimal configuration generated by setup-ntp-sync.sh
driftfile /var/lib/chrony/drift
rtcsync
makestep 1.0 3

# 上游 NTP 服务器（国内优先 + 国际冗余）
EOF

for s in "${NTP_SERVERS[@]}"; do
  echo "server $s" >> "$CHRONY_CONF"
done

cat >> "$CHRONY_CONF" <<'EOF'

# 本地日志目录
logdir /var/log/chrony
EOF

mkdir -p /var/lib/chrony /var/log/chrony

# 启用并重启 chrony
if command -v chronyd >/dev/null 2>&1 || command -v chrony >/dev/null 2>&1; then
  echo "启用并启动 chrony 服务..."
  $SYSTEMCTL enable chronyd.service 2>/dev/null || $SYSTEMCTL enable chrony.service 2>/dev/null || true
  $SYSTEMCTL restart chronyd.service 2>/dev/null || $SYSTEMCTL restart chrony.service 2>/dev/null || true
else
  echo "chrony 未成功安装，尝试启用 ntp 服务（若存在）..."
  $SYSTEMCTL enable ntpd.service 2>/dev/null || true
  $SYSTEMCTL restart ntpd.service 2>/dev/null || true
fi

# 等待服务启动
sleep 3

# 强制同步（chrony）
if command -v chronyc >/dev/null 2>&1; then
  echo "执行 chrony 强制同步：chronyc -a makestep"
  chronyc -a makestep || true
  echo
  echo "==== chronyc tracking ===="
  chronyc tracking || true
  echo
  echo "==== chronyc sources -v ===="
  chronyc sources -v || true
fi

# 若无 chrony，尝试 ntpdate
if ! command -v chronyc >/dev/null 2>&1 && command -v ntpdate >/dev/null 2>&1; then
  echo "使用 ntpdate 立即同步："
  ntpdate -u pool.ntp.org || true
fi

# 同步系统时间到硬件时钟（可选，但推荐）
echo "写回硬件时钟：hwclock --systohc"
hwclock --systohc || true

# 最终输出
echo
echo "=== timedatectl 输出 ==="
timedatectl || true
echo
echo "配置备份路径：$BACKUP_DIR"
echo "完成。若 NTP synchronized: no，请检查防火墙是否允许 UDP 123 出站/入站，或查看 chronyc sources -v 的 reach/delay/offset 指标。"
echo "=== NTP 配置流程结束 ==="